# Generated by Django 3.0 on 2022-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_auto_20220331_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
