# Generated by Django 3.1.4 on 2022-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0035_assignment_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(max_length=1000),
        ),
    ]
