# Generated by Django 3.1.4 on 2022-08-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0037_auto_20220813_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
    ]
