# Generated by Django 3.1.4 on 2022-08-13 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0039_auto_20220813_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default=datetime.datetime(2022, 8, 13, 18, 39, 55, 541992, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
