# Generated by Django 3.1.4 on 2022-08-13 18:51

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0042_auto_20220813_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=curriculum.models.save_assignment_files),
        ),
    ]
