# Generated by Django 3.1.4 on 2022-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0044_auto_20220817_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
