# Generated by Django 3.1.4 on 2022-08-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0046_auto_20220817_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='lesson',
            new_name='lesson_name',
        ),
    ]
