# Generated by Django 3.1.4 on 2022-08-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0047_auto_20220818_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='lesson_name',
            new_name='lesson',
        ),
    ]
