# Generated by Django 4.0.1 on 2022-09-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0049_remove_lesson_id_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='counter',
            field=models.IntegerField(default='1', max_length=100000),
        ),
    ]
