# Generated by Django 4.0.1 on 2022-09-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0051_ipmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='curriculum.IpModel'),
        ),
    ]
